config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
 resources :yelpits
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/yelpit.rb
class Yelpit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/yelpits_controller.rb
class YelpitsController < ApplicationController
  def index
    @yelpits = Yelpit.all
  end

  def show
    @yelpit = Yelpit.find(params[:id])
  end

  def new
    @yelpit = Yelpit.new
  end
  
  def create
    @yelpit = Yelpit.new(yelpit_params)
    if @yelpit.save
      redirect_to yelpits_path
    else
      render :new
    end 
  end

  def edit
    @yelpit = Yelpit.find(params[:id])
  end

  def update
    @yelpit = Yelpit.find(params[:id])
    if @yelpit.update(yelpit_params)
      redirect_to yelpits_path
    else
      render :edit
    end
  end

  def destroy
    Yelpit.find(params[:id]).destroy
    redirect_to yelpits_path
  end

  private
  def yelpit_params
    params.require(:yelpit).permit(:restaurant, :review, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/yelpits_helper.rb
module YelpitsHelper
end

app/views/layouts/_navbar.html.erb
  <nav>
    <div class="nav-wrapper pink">
      <a href="#" class="brand-logo">YELPit</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to  "Home", root_path %></li>
        <li><%= link_to  "Reviews", yelpits_path %></li>
        <li><%= link_to 'Add Review', new_yelpit_path%></li>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar'%>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="home">
<h1 class="homewelcome">Welcome to YELPit!!</h1>
<p class="homep">A place where you can post all of your restaurant reviews!</p>
<button class="waves-effect grey darken-3 btn"><%= link_to  "Add a Review", new_yelpit_path%></button>
</div>

app/views/yelpits/_form.html.erb
<%= form_for @yelpit do |f| %>
  <%= f.label :restaurant %>
  <%= f.text_field :restaurant %>

  <%= f.label :review %>
  <%= f.text_field :review %>

  <%= f.label :rating %>
  <%= f.text_field :rating %>

  <%= f.submit %>
<% end %>

app/views/yelpits/index.html.erb
<div class="home2">
<h1 class="showreview">See for yourself!</h1>
<% @yelpits.each do |yelpit|%>
<%= link_to  "Yelpit Review Page", new_yelpit_path%>
<%= link_to "Delete", yelpit_path(yelpit.id), method: :delete %>
<h3 class="center"><%= yelpit.restaurant %></h3>
<h4 class="center"><%= yelpit.review %></h4>
<h4 class="center"><%= yelpit.rating %></h4>
<% end %>
</div>

app/views/yelpits/new.html.erb
<h1 class="add_new">Add a New Review</h1>
<%= render 'form' %>

app/views/yelpits/show.html.erb
<h1>YelpIt!</h1>
<div>
  <div>
    <div>
      <p>Restaurant: <%= @yelpit.restaurant %></p>
      <p>Review: <%= @yelpit.review %></p>
      <p>Rating: <%= @yelpit.rating %></p>
    </div>
    <div>
      <%= link_to 'Delete', yelpit_path(@yelpit.id), method: :delete %>
      <%= link_to 'Back', yelpit_path %>
    </div>
  </div>